import React,{useEffect,useState} from "react";
import {supabase} from "@/lib/supabaseClient";
import {useAuth} from "@/lib/AuthContext";
import {DEMO_MODE,getDemoOrders,transitionDemoOrder} from "@/lib/demoMode";
import {canTransition} from "@/lib/orderStatus";
import StaffHeader from "@/components/StaffHeader";
import StatusBadge from "@/components/StatusBadge";
import OrderHistoryTimeline from "@/components/OrderHistoryTimeline";
import ReturnExchangeDialog from "@/components/ReturnExchangeDialog";
import {Loader2,MapPin,Phone,PackageCheck,Navigation,CheckCircle2,Truck,RotateCcw} from "lucide-react";
import {toast} from "@/components/ui/use-toast";
import {Button} from "@/components/ui/button";

export default function DriverDashboard(){const{user}=useAuth();const[orders,setOrders]=useState([]);const[loading,setLoading]=useState(true);const[acting,setActing]=useState(null);const[returnDialog,setReturnDialog]=useState({open:false,order:null});
const normalize=o=>({...o,items:o.order_items||o.items||[]});
const fetchOrders=async()=>{if(!user?.id)return;try{if(DEMO_MODE){setOrders(getDemoOrders().filter(o=>o.driver_id===user.id).map(normalize));return}const{data,error}=await supabase.from("orders").select("*, order_items(*)").eq("driver_id",user.id).order("created_at",{ascending:false}).limit(50);if(error)throw error;setOrders((data||[]).map(normalize))}catch(e){toast({title:"تعذر تحميل الطلبات",description:e.message,variant:"destructive"})}finally{setLoading(false)}};
useEffect(()=>{fetchOrders();if(DEMO_MODE)return undefined;const channel=supabase.channel(`driver-orders-${user?.id}`).on("postgres_changes",{event:"*",schema:"public",table:"orders",filter:`driver_id=eq.${user?.id}`},fetchOrders).subscribe();return()=>supabase.removeChannel(channel)},[user?.id]);
const doTransition=async(order,action)=>{const t=canTransition(action,order.status,user.role);if(!t)return;setActing(order.id+action);try{if(DEMO_MODE){setOrders(p=>p.map(o=>o.id===order.id?normalize(transitionDemoOrder(order.id,t.to,"driver")):o));toast({title:"تم تحديث الحالة"});return}const{data,error}=await supabase.rpc("transition_order",{p_order_id:order.id,p_new_status:t.to,p_note:`Driver action: ${action}`});if(error)throw error;setOrders(p=>p.map(o=>o.id===order.id?normalize(data):o));toast({title:"تم تحديث الحالة"})}catch(e){toast({title:"فشل التحديث",description:e.message,variant:"destructive"})}finally{setActing(null)}};
const active=orders.filter(o=>["ASSIGNED","OUT_FOR_DELIVERY","ARRIVED"].includes(o.status));const completed=orders.filter(o=>o.status==="DELIVERED");
const card=order=>{const mapsLink=order.latitude!=null&&order.longitude!=null?`https://www.google.com/maps?q=${order.latitude},${order.longitude}`:null;return <div key={order.id} className="bg-white rounded-2xl border p-4"><div className="flex justify-between items-start mb-3"><div><p className="font-mono text-xs text-muted-foreground">#{order.id.slice(-8).toUpperCase()}</p><p className="font-semibold text-sm">{order.customer_name}</p></div><StatusBadge status={order.status}/></div><div className="space-y-2 text-sm mb-3"><div className="flex gap-2 text-muted-foreground"><Phone className="w-4 h-4"/><a href={`tel:${order.customer_phone}`}>{order.customer_phone}</a></div>{order.address&&<div className="flex gap-2 text-muted-foreground"><MapPin className="w-4 h-4"/><span>{order.address}</span></div>}{order.items?.map((item,i)=><div key={i} className="flex justify-between"><span>{item.product_name} × {item.quantity}</span><span>{item.total} ر.س</span></div>)}{order.return_count>0&&<div className="flex gap-2 bg-blue-50 border border-blue-200 rounded-lg p-2 text-blue-700"><RotateCcw className="w-4 h-4"/>استلام {order.return_count} أسطوانة فارغة</div>}</div>{mapsLink&&<a href={mapsLink} target="_blank" rel="noopener noreferrer" className="flex items-center justify-center gap-2 w-full h-11 rounded-xl border mb-2"><Navigation className="w-4 h-4 text-primary"/>فتح الموقع</a>}<div className="space-y-2">{canTransition("startDelivery",order.status,user.role)&&<Button onClick={()=>doTransition(order,"startDelivery")} disabled={acting!==null} className="w-full h-12 rounded-xl">قبول الطلب وبدء التوصيل</Button>}{canTransition("arrive",order.status,user.role)&&<Button onClick={()=>doTransition(order,"arrive")} disabled={acting!==null} className="w-full h-12 rounded-xl">وصلت للعميل</Button>}{canTransition("deliver",order.status,user.role)&&<Button onClick={()=>doTransition(order,"deliver")} disabled={acting!==null} className="w-full h-12 rounded-xl">تم التسليم</Button>}</div><OrderHistoryTimeline orderId={order.id} order={order}/>{order.status==="DELIVERED"&&<Button onClick={()=>setReturnDialog({open:true,order})} variant="outline" className="w-full mt-2"><RotateCcw className="w-4 h-4 ml-2"/>مرتجع / استبدال</Button>}</div>};
return <div className="min-h-screen bg-gray-50"><StaffHeader title="لوحة السائق"/><div className="max-w-3xl mx-auto px-4 py-4">{loading?<div className="flex justify-center py-12"><Loader2 className="animate-spin"/></div>:<>{active.length>0&&<><h3 className="font-bold mb-3">الطلبات النشطة</h3><div className="space-y-3 mb-6">{active.map(card)}</div></>}{completed.length>0&&<><h3 className="font-bold mb-3">الطلبات المكتملة</h3><div className="space-y-3">{completed.map(card)}</div></>}{active.length===0&&completed.length===0&&<div className="text-center text-muted-foreground py-16"><Truck className="mx-auto w-14 h-14 mb-3"/><p>لا توجد طلبات مسندة إليك حالياً</p></div>}</>}</div><ReturnExchangeDialog order={returnDialog.order} open={returnDialog.open} onOpenChange={open=>setReturnDialog({...returnDialog,open})} onDone={fetchOrders}/></div>}
