import React,{useEffect,useState} from "react";
import {useParams,useNavigate} from "react-router-dom";
import {supabase} from "@/lib/supabaseClient";
import {useAuth} from "@/lib/AuthContext";
import {DEMO_MODE,getDemoOrder,transitionDemoOrder} from "@/lib/demoMode";
import {canTransition} from "@/lib/orderStatus";
import StaffHeader from "@/components/StaffHeader";
import StatusBadge from "@/components/StatusBadge";
import OrderHistoryTimeline from "@/components/OrderHistoryTimeline";
import {ArrowLeft,Loader2,MapPin,Phone,CheckCircle2,PackageCheck,Truck,RotateCcw} from "lucide-react";
import {toast} from "@/components/ui/use-toast";
import {Button} from "@/components/ui/button";

export default function DistributorOrderDetail(){const{id}=useParams();const navigate=useNavigate();const{user}=useAuth();const[order,setOrder]=useState(null);const[loading,setLoading]=useState(true);const[acting,setActing]=useState(null);
const normalize=o=>o?({...o,created_date:o.created_at,items:o.order_items||o.items||[]}):null;
const fetchOrder=async()=>{try{if(DEMO_MODE){setOrder(normalize(getDemoOrder(id)));return}const{data,error}=await supabase.from("orders").select("*, order_items(*)").eq("id",id).single();if(error)throw error;setOrder(normalize(data))}catch(e){console.error(e);setOrder(null)}finally{setLoading(false)}};
useEffect(()=>{fetchOrder()},[id]);
const doTransition=async(action)=>{if(!order)return;const t=canTransition(action,order.status,user.role);if(!t)return;setActing(action);try{if(DEMO_MODE){setOrder(normalize(transitionDemoOrder(order.id,t.to,"distributor")));toast({title:"تم تحديث الحالة"});return}const{data,error}=await supabase.rpc("transition_order",{p_order_id:order.id,p_new_status:t.to,p_note:`Distributor action: ${action}`});if(error)throw error;setOrder(normalize(data));toast({title:"تم تحديث الحالة"})}catch(e){toast({title:"فشل التحديث",description:e.message,variant:"destructive"})}finally{setActing(null)}};
if(loading)return <div className="min-h-screen flex items-center justify-center"><Loader2 className="animate-spin"/></div>;if(!order)return <div className="min-h-screen bg-gray-50"><StaffHeader title="تفاصيل الطلب"/><div className="p-16 text-center text-muted-foreground">لم يتم العثور على الطلب</div></div>;
const mapsLink=order.latitude!=null&&order.longitude!=null?`https://www.google.com/maps?q=${order.latitude},${order.longitude}`:null;
return <div className="min-h-screen bg-gray-50 pb-8"><StaffHeader title="تفاصيل الطلب"/><div className="max-w-3xl mx-auto px-4 py-4"><button onClick={()=>navigate("/distributor")} className="inline-flex items-center gap-1 text-sm text-muted-foreground mb-3"><ArrowLeft className="w-4 h-4 rotate-180"/>العودة للطلبات</button><div className="bg-white rounded-2xl border p-4 mb-3"><div className="flex justify-between items-center mb-3"><p className="font-mono text-xs text-muted-foreground">#{order.id.slice(-8).toUpperCase()}</p><StatusBadge status={order.status}/></div><p className="text-xs text-muted-foreground mb-3">{new Date(order.created_at).toLocaleString("ar-SA")}</p><div className="space-y-2 text-sm"><p className="font-semibold">{order.customer_name}</p><div className="flex items-center gap-2 text-muted-foreground"><Phone className="w-4 h-4"/><a href={`tel:${order.customer_phone}`}>{order.customer_phone}</a></div>{order.address&&<div className="flex gap-2 text-muted-foreground"><MapPin className="w-4 h-4"/><span>{order.address}</span></div>}{mapsLink&&<a href={mapsLink} target="_blank" rel="noopener noreferrer" className="inline-flex gap-1 text-primary text-sm font-medium"><MapPin className="w-4 h-4"/>فتح الموقع في الخرائط</a>}</div></div><div className="bg-white rounded-2xl border p-4 mb-3"><h3 className="font-semibold text-sm mb-3">المنتجات</h3><div className="space-y-2">{order.items?.map((item,idx)=><div key={idx} className="flex justify-between text-sm"><span>{item.product_name} × {item.quantity}</span><span>{item.total} ر.س</span></div>)}</div>{order.return_count>0&&<div className="mt-3 flex items-center gap-2 bg-blue-50 border border-blue-200 rounded-lg px-3 py-2 text-sm text-blue-700"><RotateCcw className="w-4 h-4"/>استلام {order.return_count} أسطوانة فارغة</div>}<div className="border-t mt-3 pt-3 space-y-1 text-sm"><div className="flex justify-between"><span>الإجمالي الفرعي</span><span>{order.subtotal} ر.س</span></div><div className="flex justify-between"><span>رسوم التوصيل</span><span>{order.delivery_fee} ر.س</span></div><div className="flex justify-between font-bold"><span>الإجمالي</span><span className="text-primary">{order.total} ر.س</span></div></div></div><OrderHistoryTimeline orderId={order.id} order={order}/><div className="space-y-2">{canTransition("accept",order.status,user.role)&&<Button onClick={()=>doTransition("accept")} disabled={acting!==null} className="w-full h-14 font-bold rounded-2xl">قبول الطلب</Button>}{canTransition("prepare",order.status,user.role)&&<Button onClick={()=>doTransition("prepare")} disabled={acting!==null} className="w-full h-14 font-bold rounded-2xl">بدء التجهيز</Button>}{canTransition("ready",order.status,user.role)&&<Button onClick={()=>doTransition("ready")} disabled={acting!==null} className="w-full h-14 font-bold rounded-2xl">جاهز للتوصيل</Button>}</div></div></div>}
