import React,{useEffect,useState} from "react";
import {Link} from "react-router-dom";
import {supabase} from "@/lib/supabaseClient";
import {DEMO_MODE,getDemoOrders} from "@/lib/demoMode";
import {useAuth} from "@/lib/AuthContext";
import {STATUS_LABELS_AR} from "@/lib/orderStatus";
import {Bell,Check} from "lucide-react";
import {toast} from "@/components/ui/use-toast";
function Loader(){return <div className="w-6 h-6 border-4 border-gray-200 border-t-primary rounded-full animate-spin"/>}
export default function Notifications(){const{user}=useAuth();const[n,setN]=useState([]);const[loading,setLoading]=useState(true);useEffect(()=>{if(!user?.id)return;let active=true;if(DEMO_MODE){const orders=getDemoOrders().filter(o=>user.role==="customer"?o.customer_id===user.id:user.role==="driver"?o.driver_id===user.id:true);const rows=orders.flatMap(o=>(o.history||[]).map(h=>({id:`${o.id}-${h.id}`,title:STATUS_LABELS_AR[h.new_status]||h.new_status,body:`طلب #${o.id.slice(-8).toUpperCase()} — ${h.note||"تحديث الحالة"}`,created_at:h.created_at,read:false}))).sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));setN(rows);setLoading(false);return undefined}const load=async()=>{try{const{data,error}=await supabase.from("notifications").select("*").eq("user_id",user.id).order("created_at",{ascending:false}).limit(50);if(error)throw error;if(active)setN(data||[])}catch(e){toast({title:"تعذر تحميل الإشعارات",description:e.message,variant:"destructive"})}finally{if(active)setLoading(false)}};load();const c=supabase.channel(`notifications-${user.id}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"notifications",filter:`user_id=eq.${user.id}`},load).subscribe();return()=>{active=false;supabase.removeChannel(c)}},[user?.id,user?.role]);const read=async()=>{if(DEMO_MODE){setN(x=>x.map(a=>({...a,read:true})));return}const{error}=await supabase.from("notifications").update({read:true}).eq("user_id",user.id).eq("read",false);if(error)toast({title:"فشل التحديث",variant:"destructive"});else setN(x=>x.map(a=>({...a,read:true})))};const home=user?.role==="customer"?"/":user?.role==="distributor"?"/distributor":user?.role==="driver"?"/driver":"/admin";return <div className="min-h-screen bg-gray-50"><header className="sticky top-0 z-40 bg-white border-b"><div className="max-w-md mx-auto px-4 h-14 flex items-center justify-between"><Link to={home} className="text-sm text-muted-foreground">رجوع</Link><h1 className="font-bold">الإشعارات</h1><button onClick={read} className="text-sm text-primary font-medium">تعليم الكل كمقروء</button></div></header><div className="max-w-md mx-auto px-4 py-4">{loading?<div className="flex justify-center py-12"><Loader/></div>:n.length===0?<div className="flex flex-col items-center py-16 text-muted-foreground"><Bell className="w-14 h-14 mb-3"/><p>لا توجد إشعارات</p></div>:<div className="space-y-2">{n.map(x=><div key={x.id} className={`rounded-2xl border p-4 flex gap-3 ${x.read?"bg-white":"bg-primary/5 border-primary/20"}`}><div className="w-9 h-9 rounded-full flex items-center justify-center flex-shrink-0">{x.read?<Check className="w-4 h-4"/>:<Bell className="w-4 h-4"/>}</div><div><p className="font-semibold text-sm">{x.title}</p><p className="text-sm text-muted-foreground">{x.body}</p><p className="text-xs text-muted-foreground mt-1">{new Date(x.created_at).toLocaleString("ar-SA")}</p></div></div>)}</div>}</div></div>}
