import React, { useState } from "react";
import { Link } from "react-router-dom";
import { supabase } from "@/lib/supabaseClient";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { UserPlus, Mail, Loader2 } from "lucide-react";
import { InputOTP, InputOTPGroup, InputOTPSlot } from "@/components/ui/input-otp";
import AuthLayout from "@/components/AuthLayout";
import GoogleIcon from "@/components/GoogleIcon";
import { toast } from "@/components/ui/use-toast";
import { safeReturnTo } from "@/lib/authReturnTo";

export default function Register() {
  const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [confirmPassword,setConfirmPassword]=useState(""); const [error,setError]=useState(""); const [loading,setLoading]=useState(false); const [showOtp,setShowOtp]=useState(false); const [otpCode,setOtpCode]=useState("");
  const handleSubmit=async e=>{e.preventDefault();setError("");if(password!==confirmPassword)return setError("كلمتا المرور غير متطابقتين");setLoading(true);try{const {data,error}=await supabase.auth.signUp({email,password});if(error)throw error;if(data.session)window.location.href=safeReturnTo();else setShowOtp(true);}catch(err){setError(err.message||"فشل إنشاء الحساب");}finally{setLoading(false);}};
  const handleVerify=async()=>{setError("");setLoading(true);try{const {error}=await supabase.auth.verifyOtp({email,token:otpCode,type:"signup"});if(error)throw error;window.location.href=safeReturnTo();}catch(err){setError(err.message||"رمز التحقق غير صحيح");}finally{setLoading(false);}};
  const handleResend=async()=>{setError("");const {error}=await supabase.auth.resend({type:"signup",email});if(error)setError(error.message);else toast({title:"تم إرسال الرمز",description:"تحقق من بريدك الإلكتروني للحصول على الرمز الجديد."});};
  const handleGoogle=async()=>{const {error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${window.location.origin}${safeReturnTo()}`}});if(error)setError(error.message);};
  if(showOtp)return <AuthLayout icon={Mail} title="تحقق من بريدك الإلكتروني" subtitle={`أرسلنا رمزاً إلى ${email}`}><>{error&&<div className="mb-4 p-3 rounded-lg bg-destructive/10 text-destructive text-sm">{error}</div>}<div className="flex justify-center mb-6"><InputOTP maxLength={6} value={otpCode} onChange={setOtpCode} autoFocus autoComplete="one-time-code"><InputOTPGroup><InputOTPSlot index={0}/><InputOTPSlot index={1}/><InputOTPSlot index={2}/><InputOTPSlot index={3}/><InputOTPSlot index={4}/><InputOTPSlot index={5}/></InputOTPGroup></InputOTP></div><Button className="w-full h-12 font-medium" onClick={handleVerify} disabled={loading||otpCode.length<6}>{loading?<><Loader2 className="w-4 h-4 ml-2 animate-spin"/>جاري التحقق...</>:"تحقق"}</Button><p className="text-center text-sm text-muted-foreground mt-4">لم يصلك الرمز؟ <button onClick={handleResend} className="text-primary font-medium hover:underline">إعادة إرسال</button></p></></AuthLayout>;
  return <AuthLayout icon={UserPlus} title="أنشئ حسابك" subtitle="سجّل للبدء" footer={<>لديك حساب بالفعل؟ <Link to="/login" className="text-primary font-medium hover:underline">تسجيل الدخول</Link></>}><Button variant="outline" className="w-full h-12 text-sm font-medium mb-6" onClick={handleGoogle}><GoogleIcon className="w-5 h-5 ml-2"/>المتابعة عبر Google</Button><div className="relative mb-6"><div className="absolute inset-0 flex items-center"><div className="w-full border-t border-border"/></div><div className="relative flex justify-center text-xs uppercase"><span className="bg-card px-3 text-muted-foreground">أو</span></div></div>{error&&<div className="mb-4 p-3 rounded-lg bg-destructive/10 text-destructive text-sm">{error}</div>}<form onSubmit={handleSubmit} className="space-y-4"><div className="space-y-2"><Label htmlFor="email">البريد الإلكتروني</Label><Input id="email" type="email" autoComplete="email" autoFocus value={email} onChange={e=>setEmail(e.target.value)} required/></div><div className="space-y-2"><Label htmlFor="password">كلمة المرور</Label><Input id="password" type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} required/></div><div className="space-y-2"><Label htmlFor="confirm">تأكيد كلمة المرور</Label><Input id="confirm" type="password" autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} required/></div><Button type="submit" className="w-full h-12 font-medium" disabled={loading}>{loading?<><Loader2 className="w-4 h-4 ml-2 animate-spin"/>جاري إنشاء الحساب...</>:"إنشاء حساب"}</Button></form></AuthLayout>;
}
