-- Function execution hardening
revoke all on function public.set_updated_at() from public, anon, authenticated;
revoke all on function public.set_order_route_metadata() from public, anon, authenticated;
revoke all on function public.set_payment_updated_at() from public, anon, authenticated;
revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.create_invoice_after_order() from public, anon, authenticated;
revoke all on function public.notify_inventory_thresholds() from public, anon, authenticated;
revoke all on function public.capture_order_distributor() from public, anon, authenticated;
revoke all on function public.reserve_stock(uuid, integer, uuid) from public, anon, authenticated;
revoke all on function public.release_stock(uuid, integer, uuid) from public, anon, authenticated;
revoke all on function public.consume_stock(uuid, integer, uuid) from public, anon, authenticated;
revoke all on function public.is_admin() from public, anon, authenticated;
revoke all on function public.assign_order_smart(uuid, uuid) from public, anon;
revoke all on function public.create_order(text, text, text, public.payment_method, jsonb, numeric, numeric, numeric) from public, anon;
revoke all on function public.ensure_invoice_for_order(uuid) from public, anon;
revoke all on function public.get_order_billing(uuid) from public, anon;
revoke all on function public.manage_inventory(text, uuid, integer, uuid, text) from public, anon;
revoke all on function public.process_return_exchange(uuid, text, jsonb, jsonb, text) from public, anon;
revoke all on function public.record_payment_result(uuid, text, text, numeric, public.payment_status, text, jsonb) from public, anon;
revoke all on function public.start_card_payment(uuid) from public, anon;
revoke all on function public.transfer_inventory_to_driver(uuid, uuid, integer, text) from public, anon;
revoke all on function public.transition_order(uuid, public.order_status, text) from public, anon;
revoke all on function public.update_my_profile(text, text) from public, anon;
grant execute on function public.assign_order_smart(uuid, uuid) to authenticated;
grant execute on function public.create_order(text, text, text, public.payment_method, jsonb, numeric, numeric, numeric) to authenticated;
grant execute on function public.ensure_invoice_for_order(uuid) to authenticated;
grant execute on function public.get_order_billing(uuid) to authenticated;
grant execute on function public.manage_inventory(text, uuid, integer, uuid, text) to authenticated;
grant execute on function public.process_return_exchange(uuid, text, jsonb, jsonb, text) to authenticated;
grant execute on function public.record_payment_result(uuid, text, text, numeric, public.payment_status, text, jsonb) to authenticated;
grant execute on function public.start_card_payment(uuid) to authenticated;
grant execute on function public.transfer_inventory_to_driver(uuid, uuid, integer, text) to authenticated;
grant execute on function public.transition_order(uuid, public.order_status, text) to authenticated;
grant execute on function public.update_my_profile(text, text) to authenticated;